### ISSUE TITLE
Compile problem

### ISSUE THREAD

**Issue by czerwony03** [sergeii/swat-utils#1]
Hi,
I'm trying to compile this script, but i don't know how.

I tried with umake but i dont know if i prepare it right because im getting error:

----- Core (Release)
----- Engine (Release)
'Engine' is not a DLL package; can't find export 'intAPlayerControllerexecSetViewTarget'

History: UPackage::GetDllExport <- UFunction::Bind <- UField::PostLoad <- UStruct::PostLoad <- UFunction::PostLoad <- UObject::ConditionalPostLoad [(Function Engine.PlayerController.SetViewTarget)] <- PostLoadObjects <- UObject::EndLoad <- UObject::LoadPackage <- OpenPackage <- CompilePackage <- LoadEditPackages <- UMakeCommandlet::Main

Exiting due to error

Can you explain me what i am doing wrong and how to compile it properly?

Greetings from Poland.

**Comment by czerwony03** [comment]
Ok, i learn a bit and go forward ;-)
Now I'm getting that error:
D:\Gry\SWAT 4_2\ContentExpansion\System>ucc make
--------------------Utils - Release--------------------
Analyzing...
Superclass Object of class ArrayUtils not found (if superclass is in a different package, did you fully specify it with "extends <OtherPackage>.Object" ?)

History: CompilePackage <- LoadEditPackages <- UMakeCommandlet::Main

Exiting due to error

**Comment by sergeii** [comment]
Hello.

Make sure to include the following lines under **[Editor.EditorEngine]** in UCC.ini

EditPackages=Core
EditPackages=Engine
EditPackages=IGEffectsSystem
EditPackages=IGVisualEffectsSubsystem
EditPackages=IGSoundEffectsSubsystem
EditPackages=Editor
EditPackages=UWindow
EditPackages=GUI
EditPackages=SwatEd
EditPackages=IpDrv
EditPackages=Scripting
EditPackages=AICommon
EditPackages=Tyrion
EditPackages=SwatAIAwareness
EditPackages=SwatAICommon
EditPackages=Gameplay
EditPackages=RWOSupport
EditPackages=SwatGame
EditPackages=SwatEquipment
EditPackages=SwatObjectives
EditPackages=SwatProcedures
EditPackages=SwatGui
ServerActors=Utils.Package

**Comment by czerwony03** [comment]
Thx for fast reply.
On SWAT4 (Content) everything is ok now.
But on SWAT4 TSS (ContentExpansion) still can't compile:

Heading: --------------------Core - Release--------------------
Log: Success: Everything is up to date
Heading: --------------------Engine - Release--------------------
Warning: Missing Class Class Engine.HkMeshProxy
Warning: Missing Class Class Engine.Polys
Warning: Missing Class Class Engine.KMeshProps
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing ArrayProperty ArrayProperty Engine.VoiceChatReplicationInfo.Channels
Warning: Missing Class Class Engine.StatsInterface
Warning: Missing Class Class Engine.StatsBase
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing IntProperty IntProperty Engine.VoiceChatRoom.ChannelIndex
Warning: Missing Class Class Engine.IVisionEnhancement
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing ArrayProperty ArrayProperty Engine.VoiceChatRoom.Children
Warning: Missing Class Class Engine.StatsBase
Warning: Missing ObjectProperty ObjectProperty Engine.StatsBase.Level
Warning: Missing Class Class Engine.HkMeshProxy
Warning: Missing Class Class Engine.Polys
Warning: Missing Class Class Engine.KMeshProps
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing ObjectProperty ObjectProperty Engine.VoiceChatRoom.GRI
Warning: Missing Class Class Engine.Polys
Warning: Missing Class Class Engine.AnimNotify_Lightstick
Warning: Missing Class Class Engine.AnimNotify_Melee
Warning: Missing Class Class Engine.HkMeshProxy
Warning: Missing Class Class Engine.KMeshProps
Warning: Missing Class Class Engine.AmmoBandolierBase
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.RemoveVoiceChannel
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Function Function Engine.VoiceChatRoom.GetTeam
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing ObjectProperty ObjectProperty Engine.VoiceChatRoom.VoiceChatManager
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Enum Enum Engine.VoiceChatRoom.EJoinChatResult
Warning: Missing Class Class Engine.IReactToDazingWeapon
Warning: Missing Class Class Engine.HkMeshProxy
Warning: Missing Class Class Engine.Polys
Warning: Missing Class Class Engine.KMeshProps
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.CreateNewVoiceChannel
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.GetChannelAt
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.GetChannel
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.GetChannelIndex
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.InitChannels
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.PostNetBeginPlay
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.PostBeginPlay
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing ClassProperty ClassProperty Engine.VoiceChatReplicationInfo.ChatRoomClass
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing ObjectProperty ObjectProperty Engine.VoiceChatReplicationInfo.GRI
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Function Function Engine.VoiceChatRoom.RemoveChild
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Function Function Engine.VoiceChatRoom.AddChild
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Function Function Engine.VoiceChatRoom.SetTeam
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Function Function Engine.VoiceChatRoom.RemoveMember
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Function Function Engine.VoiceChatRoom.AddMember
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Function Function Engine.VoiceChatRoom.LeaveChannel
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Function Function Engine.VoiceChatRoom.JoinChannel
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Function Function Engine.VoiceChatRoom.IsMember
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Function Function Engine.VoiceChatRoom.CanJoinChannel
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Function Function Engine.VoiceChatRoom.GetTitle
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Function Function Engine.VoiceChatRoom.GetMask
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing StrProperty StrProperty Engine.VoiceChatRoom.Password
Warning: Missing Class Class Engine.StatsBase
Warning: Missing Function Function Engine.StatsBase.StatInt
Warning: Missing Class Class Engine.StatsBase
Warning: Missing Function Function Engine.StatsBase.StatStr
Warning: Missing Class Class Engine.StatsBase
Warning: Missing Function Function Engine.StatsBase.SetPlayer
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing ObjectProperty ObjectProperty Engine.VoiceChatRoom.Parent
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing BoolProperty BoolProperty Engine.VoiceChatRoom.bLocal
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Function Function Engine.VoiceChatRoom.GetMembers
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Function Function Engine.VoiceChatRoom.GetPassword
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Function Function Engine.VoiceChatRoom.IsPublicChannel
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Function Function Engine.VoiceChatRoom.IsPrivateChannel
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Function Function Engine.VoiceChatRoom.IsFull
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.AddVoiceChatter
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.RemoveVoiceChatter
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.CanJoinChannel
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.JoinChannel
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.JoinChannelAt
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.LeaveChannel
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.AddVoiceChannel
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.GetChannelCount
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.GetChannelMembers
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.GetChannelMembersAt
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.GetMemberChannels
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.GetChannels
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.GetPublicChannels
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.GetPlayerChannels
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.GetPublicChannelCount
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.GetPlayerChannelCount
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.IsMember
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.DestroyVoiceChannel
Warning: Missing Class Class Engine.Polys
Warning: Missing Class Class Engine.HkMeshProxy
Warning: Missing Class Class Engine.Polys
Warning: Missing Class Class Engine.HkMeshProxy
Warning: Missing Class Class Engine.HkMeshProxy
Warning: Missing Class Class Engine.Polys
Warning: Missing Class Class Engine.IReactToDazingWeapon
Warning: Missing Class Class Engine.HkMeshProxy
Warning: Missing Class Class Engine.Polys
Warning: Missing Class Class Engine.KMeshProps
Warning: Missing Class Class Engine.AmmoBandolierBase
Warning: Missing Class Class Engine.IVisionEnhancement
Warning: Missing Class Class Engine.HkMeshProxy
Warning: Missing Class Class Engine.AnimNotify_Melee
Warning: Missing Class Class Engine.AnimNotify_Lightstick
Critical: appError called:
Critical: Object BoolProperty bEnableVoiceChat created in Package instead of Field
Exit: Executing UObject::StaticShutdownAfterError
Critical: UObject::StaticAllocateObject [(BoolProperty bEnableVoiceChat)]
Critical: UObject::StaticConstructObject
Critical: ULinkerLoad::CreateExport [(bEnableVoiceChat 3294460)]
Critical: ULinkerLoad::LoadAllObjects [(LinkerLoad Transient.LinkerLoad1)]
Critical: UObject::LoadPackage
Critical: OpenPackage
Critical: CompilePackage
Critical: LoadEditPackages
Critical: UMakeCommandlet::Main
Exit: Exiting.
Log: Waiting for file streaming thread to finish...
Uninitialized: Name subsystem shut down
Uninitialized: Log file closed, 05/29/15 17:29:44

**Comment by sergeii** [comment]
It looks like you are using the wrong Source directory.

**Comment by czerwony03** [comment]
Can you give me proper one?

**Comment by sergeii** [comment]
Here is it https://dl.dropboxusercontent.com/u/59791424/SWAT4_SDK.zip

**Comment by czerwony03** [comment]
Nothing changed :-\

Log: Log file open, 06/02/15 10:46:32
Init: ----------------------------------------
Init: SWAT VERSION NUMBER: 1.0
Init: ----------------------------------------
Init: Compiled: Nov 22 2005 12:00:47
Init: Command line: -nobind
Init: Base directory: D:\Gry\SWAT4\ContentExpansion2\System\
Init: Character set: Unicode
Init: Found startup configuration: StartupUCC.ini
Init: Adding FilePath: ....\Source\Game\System;....\Source\Unreal\System;....\Content;....\Content\System;....\Content\Classes;....\ContentExpansion2;....\ContentExpansion2\System;....\ContentExpansion2\Classes;..........\Swat4Expansion\Source\Game\System;..........\Swat4Expansion\Source\Unreal\System;..........\Swat4Expansion\Content;..........\Swat4Expansion\Content\System;..........\Swat4Expansion\Content\Classes;..........\Swat4Expansion\ContentExpansion2;..........\Swat4Expansion\ContentExpansion2\System;..........\Swat4Expansion\ContentExpansion2\Classes
Log: Bound to Core.dll
Init: Object subsystem initialized
Init: Computer: NOWYKOMP
Init: User: Mriusz
Init: CPU Page size=4096, Processors=2
Init: CPU Detected: PentiumPro-class processor (GenuineIntel)
Init: CPU Features: CMov FPU RDTSC PAE MMX SSE
Init: CPU Speed=2137.076255 MHz
Init: Memory total: Phys=2097151K Pagef=4194303K Virt=2097024K
Init: Working set: 32000 / 159000
Log: Bound to ScriptCompiler.dll
Log: Executing Class ScriptCompiler.MakeCommandlet
Heading: --------------------Core - Release--------------------
Log: Success: Everything is up to date
Heading: --------------------Engine - Release--------------------
Warning: Missing Class Class Engine.HkMeshProxy
Warning: Missing Class Class Engine.Polys
Warning: Missing Class Class Engine.KMeshProps
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing ArrayProperty ArrayProperty Engine.VoiceChatReplicationInfo.Channels
Warning: Missing Class Class Engine.StatsInterface
Warning: Missing Class Class Engine.StatsBase
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing IntProperty IntProperty Engine.VoiceChatRoom.ChannelIndex
Warning: Missing Class Class Engine.IVisionEnhancement
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing ArrayProperty ArrayProperty Engine.VoiceChatRoom.Children
Warning: Missing Class Class Engine.StatsBase
Warning: Missing ObjectProperty ObjectProperty Engine.StatsBase.Level
Warning: Missing Class Class Engine.HkMeshProxy
Warning: Missing Class Class Engine.Polys
Warning: Missing Class Class Engine.KMeshProps
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing ObjectProperty ObjectProperty Engine.VoiceChatRoom.GRI
Warning: Missing Class Class Engine.Polys
Warning: Missing Class Class Engine.AnimNotify_Lightstick
Warning: Missing Class Class Engine.AnimNotify_Melee
Warning: Missing Class Class Engine.HkMeshProxy
Warning: Missing Class Class Engine.KMeshProps
Warning: Missing Class Class Engine.AmmoBandolierBase
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.RemoveVoiceChannel
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Function Function Engine.VoiceChatRoom.GetTeam
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing ObjectProperty ObjectProperty Engine.VoiceChatRoom.VoiceChatManager
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Enum Enum Engine.VoiceChatRoom.EJoinChatResult
Warning: Missing Class Class Engine.IReactToDazingWeapon
Warning: Missing Class Class Engine.HkMeshProxy
Warning: Missing Class Class Engine.Polys
Warning: Missing Class Class Engine.KMeshProps
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.CreateNewVoiceChannel
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.GetChannelAt
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.GetChannel
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.GetChannelIndex
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.InitChannels
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.PostNetBeginPlay
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.PostBeginPlay
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing ClassProperty ClassProperty Engine.VoiceChatReplicationInfo.ChatRoomClass
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing ObjectProperty ObjectProperty Engine.VoiceChatReplicationInfo.GRI
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Function Function Engine.VoiceChatRoom.RemoveChild
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Function Function Engine.VoiceChatRoom.AddChild
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Function Function Engine.VoiceChatRoom.SetTeam
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Function Function Engine.VoiceChatRoom.RemoveMember
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Function Function Engine.VoiceChatRoom.AddMember
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Function Function Engine.VoiceChatRoom.LeaveChannel
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Function Function Engine.VoiceChatRoom.JoinChannel
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Function Function Engine.VoiceChatRoom.IsMember
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Function Function Engine.VoiceChatRoom.CanJoinChannel
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Function Function Engine.VoiceChatRoom.GetTitle
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Function Function Engine.VoiceChatRoom.GetMask
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing StrProperty StrProperty Engine.VoiceChatRoom.Password
Warning: Missing Class Class Engine.StatsBase
Warning: Missing Function Function Engine.StatsBase.StatInt
Warning: Missing Class Class Engine.StatsBase
Warning: Missing Function Function Engine.StatsBase.StatStr
Warning: Missing Class Class Engine.StatsBase
Warning: Missing Function Function Engine.StatsBase.SetPlayer
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing ObjectProperty ObjectProperty Engine.VoiceChatRoom.Parent
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing BoolProperty BoolProperty Engine.VoiceChatRoom.bLocal
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Function Function Engine.VoiceChatRoom.GetMembers
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Function Function Engine.VoiceChatRoom.GetPassword
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Function Function Engine.VoiceChatRoom.IsPublicChannel
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Function Function Engine.VoiceChatRoom.IsPrivateChannel
Warning: Missing Class Class Engine.VoiceChatRoom
Warning: Missing Function Function Engine.VoiceChatRoom.IsFull
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.AddVoiceChatter
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.RemoveVoiceChatter
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.CanJoinChannel
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.JoinChannel
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.JoinChannelAt
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.LeaveChannel
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.AddVoiceChannel
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.GetChannelCount
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.GetChannelMembers
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.GetChannelMembersAt
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.GetMemberChannels
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.GetChannels
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.GetPublicChannels
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.GetPlayerChannels
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.GetPublicChannelCount
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.GetPlayerChannelCount
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.IsMember
Warning: Missing Class Class Engine.VoiceChatReplicationInfo
Warning: Missing Function Function Engine.VoiceChatReplicationInfo.DestroyVoiceChannel
Warning: Missing Class Class Engine.Polys
Warning: Missing Class Class Engine.HkMeshProxy
Warning: Missing Class Class Engine.Polys
Warning: Missing Class Class Engine.HkMeshProxy
Warning: Missing Class Class Engine.HkMeshProxy
Warning: Missing Class Class Engine.Polys
Warning: Missing Class Class Engine.IReactToDazingWeapon
Warning: Missing Class Class Engine.HkMeshProxy
Warning: Missing Class Class Engine.Polys
Warning: Missing Class Class Engine.KMeshProps
Warning: Missing Class Class Engine.AmmoBandolierBase
Warning: Missing Class Class Engine.IVisionEnhancement
Warning: Missing Class Class Engine.HkMeshProxy
Warning: Missing Class Class Engine.AnimNotify_Melee
Warning: Missing Class Class Engine.AnimNotify_Lightstick
Critical: appError called:
Critical: Object BoolProperty bEnableVoiceChat created in Package instead of Field
Exit: Executing UObject::StaticShutdownAfterError
Critical: UObject::StaticAllocateObject [(BoolProperty bEnableVoiceChat)]
Critical: UObject::StaticConstructObject
Critical: ULinkerLoad::CreateExport [(bEnableVoiceChat 3294460)]
Critical: ULinkerLoad::LoadAllObjects [(LinkerLoad Transient.LinkerLoad1)]
Critical: UObject::LoadPackage
Critical: OpenPackage
Critical: CompilePackage
Critical: LoadEditPackages
Critical: UMakeCommandlet::Main
Exit: Exiting.
Log: Waiting for file streaming thread to finish...
Uninitialized: Name subsystem shut down
Uninitialized: Log file closed, 06/02/15 10:46:39
